### ISSUE TITLE
Infinite MapDiffBot Action

### ISSUE THREAD

**Issue by TemporalOroboros** [tgstation/MapDiffBot#126]
Note that inconsistencies/errors in renderings should be reported on the upstream repository: https://github.com/SpaceManiac/SpacemanDMM

https://github.com/tgstation/tgstation/pull/54801/checks?check_run_id=1355391765

It's been two weeks and it's still going...

**Comment by AffectedArc07** [comment]
MDB hard-crashed during this render. It will **never** complete, and stay like this forever. Youll need to push a new commit.
