### ISSUE TITLE
cannot reference variables in this context error when using macros in DMM

### ISSUE THREAD

**Issue by Sovexe** [tgstation/MapDiffBot#129]
If you have macros in your dmm file MapDiffBot is unable to provide renders

example from goonstation z2.dmm of a macro that will cause this issue

```dm
"dkP" = (
/obj/landmark/escape_pod_succ{
	shuttle = SHUTTLE_SOUTH
	},
/turf/space/shuttle_transit,
/area/shuttle_transit_space/north)
```

https://mdb.affectedarc07.co.uk/Files/252047483/2013182595/0/logs.txt

**Comment by AffectedArc07** [comment]
Issue with spacemanDMM, not our code. Please report on

https://github.com/Spacemaniac/SpacemanDMM
