### ISSUE TITLE
Cannot use idents during simple_evaluate

### ISSUE THREAD

**Issue by 81Denton** [tgstation/MapDiffBot#46]
PR: https://github.com/tgstation/tgstation/pull/36964
Job log: https://dextraspace.net/MapDiffBot/Files/3234987/36964/0/logs.txt

StdErr:
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: DMError { location: Location { file: FileId(4294967295), line: 0, column: 0 }, severity: Error, desc: "cannot use idents during simple_evaluate", cause: None }', /checkout/src/libcore/result.rs:916:5

note: Run with `RUST_BACKTRACE=1` for a backtrace.

https://dextraspace.net/MapDiffBot/Files/3234987/36964/0/after.png gives a 404 error.

**Comment by Cyberboss** [comment]
Given that this is somewhat fixed via the line numbers it should be manageble
