### ISSUE TITLE
Error viewing old/new pictures

### ISSUE THREAD

**Issue by JohnGinnane** [tgstation/MapDiffBot#50]
Comment: https://github.com/HippieStation/HippieStation/pull/7580#issuecomment-385938947

Before: https://dextraspace.net/MapDiffBot/Files/84665083/7580/0/before.png
After: https://dextraspace.net/MapDiffBot/Files/84665083/7580/0/after.png

**Comment by Cyberboss** [comment]
Seems like dmm-tools panicked: https://dextraspace.net/MapDiffBot/Files/84665083/7580/0/logs.txt It shouldn't have posted those links

@SpaceManiac

**Comment by SpaceManiac** [comment]
Fixed in https://github.com/SpaceManiac/SpacemanDMM/commit/d5b27f10655288280f15fb85a191db03c43ba4fd

**Comment by Cyberboss** [comment]
Given the move to github checks, this can be closed
