### ISSUE TITLE
0KB file

### ISSUE THREAD

**Issue by ShizCalev** [tgstation/MapDiffBot#74]
https://github.com/tgstation/tgstation/pull/37919/checks

_maps/RandomRuins/SpaceRuins/oldteleporter.dmm 's after.png is erroring out. Tryed rerunning, same issue.

http://mapdiffbot.dextraspace.net/Files/3234987/1119740/5/after.png

**Comment by Cyberboss** [comment]
@SpaceManiac http://mapdiffbot.dextraspace.net/Files/3234987/1119740/5/logs.txt second task exited with code 137

**Comment by Cyberboss** [comment]
Actually this is strange, considering https://github.com/tgstation/tgstation/pull/37936 works
